<?php

namespace App\Filament\Resources\TeacherResource\Pages;

use App\Enums\Role;
use App\Filament\Resources\TeacherResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateTeacher extends CreateRecord
{
    protected static string $resource = TeacherResource::class;

    protected function getHeaderActions(): array
    {
        return [

        ];
    }

    protected function handleRecordCreation(array $data): Model
    {
        data_set($data, 'role', Role::Teacher);
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
